/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-maddy.h
 #	source generated by 4D Plugin Wizard
 #	Project : maddy
 #	author : miyako
 #	2025/06/17
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_MADDY_H
#define PLUGIN_MADDY_H

#include "4DPluginAPI.h"
#include "maddy/parser.h"
#include "C_TEXT.h"
#include "4DPlugin-JSON.h"

#pragma mark -

static void _maddy(PA_PluginParameters params);

#endif /* PLUGIN_MADDY_H */
